application: app-example
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

libraries:
- name: endpoints
  version: "latest"

handlers:
- url: /_ah/spi/.*
  script: run.api

- url: /*
  script: run.app

- url: /media
  static_dir: todo_app/media
